version: '3.8'

services:
  meilisearch:
    image: getmeili/meilisearch:v1.7.6
    ports:
      - 7700:7700
    environment:
      MEILI_ENV: development
    volumes:
      - ./meili_data:/meili_data
