name: Prepare
description: Prepares the repo

runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v2
      with:
      version: 8

    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: "pnpm"

    - name: install
      run: pnpm i
