name: tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  run-unit-tests:
    environment: testing
    env:
      PORT: ${{vars.PORT}}
      DB_JSON_FILE_PATH: ${{vars.DB_JSON_FILE_PATH}}

    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"

      - name: typecheck
        run: pnpm typecheck

      - name: unit tests
        run: pnpm test
