name: tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  run-tests:
    environment: testing
    env:
      PORT: ${{vars.PORT}}
      DB_JSON_FILE_PATH: ${{vars.DB_JSON_FILE_PATH}}

    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/prepare

      - name: typecheck
        run: pnpm typecheck

      - name: unit tests
        run: pnpm test
